AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Discord event schedule
  
  Schedules discord events

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  ScheduleEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: DiscordEventScheduler
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 1 1 ? 1970)
      Environment:
        Variables:
          PARAM1: VALUE

Outputs:
  ScheduleEventFunction:
    Description: "ScheduleEventFunction ARN"
    Value: !GetAtt ScheduleEventFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for ScheduleEventFunction function"
    Value: !GetAtt ScheduleEventFunctionRole.Arn
